version: "2.1"
services:
  sender:
    build: ../
    volumes:
      - ../emails:/src/emails
      - ../templates:/src/templates
      - ../app.js:/src/app.js
    env_file: ../.env
    command: node app.js
